services:
    node-red:
        restart: unless-stopped
        container_name: node-red
        image: nodered/node-red:latest
        ports:
            - 1880:1880
            - 1883:1883
        working_dir: /app
        user: "${UID}:${GID}"
        volumes:
            - node-red-data:/app
        entrypoint: ["node-red"]
        
volumes:
    node-red-data:
        external: true
